### ISSUE TITLE
Is it possible run on background?

### ISSUE THREAD

**Issue by KyongSik-Yoon** [ZOXEXIVO/cpu_tray#1]
When I run cputray.exe command line window is popped.
If close that CPU usage also not displayed on task bar.

**Comment by ZOXEXIVO** [comment]
Hmm. Its popped for about 100-200ms and hide automatically
This code hides console window - https://github.com/ZOXEXIVO/cpu_tray/blob/master/src/main.rs#L12

Which OS? 
Did you try copy shortcut for this exe to %AppData%\Microsoft\Windows\Start Menu\Programs\Startup ?

**Comment by KyongSik-Yoon** [comment]
My OS is Windows 11 and just double clicked exe file.
I will try copy short cut to startup directory.

**Comment by ZOXEXIVO** [comment]
In new Release (0.6), I rewrote some things and now it work without Console windows flashing
https://github.com/ZOXEXIVO/cpu_tray/releases/tag/0.6

Thanks for using
